"""empty message

Revision ID: 69fd1754c380
Revises: fc7b405e1b11
Create Date: 2021-08-07 18:41:11.014114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fd1754c380'
down_revision = 'fc7b405e1b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hero_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('comics_appeared_in', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('super_power', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('owner_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_token'], ['user.owner_token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('hero')
    # ### end Alembic commands ###
